require("core.plugin_configs.lsp_config")
require("core.plugin_configs.telescope")
require("core.plugin_configs.completion")
require("core.plugin_configs.feline")
require("core.plugin_configs.sidebar")
--require("core.plugin_configs.galaxyline")
